// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRP0zuZX72FmoTHbxsU1rl37vm0nJl2mk',
    appId: '1:434782527915:web:1db5f09af08256ebdfb2ee',
    messagingSenderId: '434782527915',
    projectId: 'my-budget-2600c',
    authDomain: 'my-budget-2600c.firebaseapp.com',
    storageBucket: 'my-budget-2600c.appspot.com',
    measurementId: 'G-QGBERLL1N2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIm8kpwBJabSieE36btSKgsDIIRi4EV0o',
    appId: '1:434782527915:android:c78b7cff08da15f0dfb2ee',
    messagingSenderId: '434782527915',
    projectId: 'my-budget-2600c',
    storageBucket: 'my-budget-2600c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWacs5WNiLR5DueWywXT7vlruOH_xs30Q',
    appId: '1:434782527915:ios:08c24bd659b77c14dfb2ee',
    messagingSenderId: '434782527915',
    projectId: 'my-budget-2600c',
    storageBucket: 'my-budget-2600c.appspot.com',
    iosBundleId: 'com.codedude.myBudget',
  );
}
